version: '3.8'
services:
  web:
    build: .
    volumes:
     - .:/src
    depends_on:
     - redis_service
    env_file:
      - redis.env
      
      
  redis_service:
    image: redis
    ports:
     - "6379:6379"
    
